<?php
/**
 * SearchConfigSchemaAttributeType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Search Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SearchConfigSchemaAttributeType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchConfigSchemaAttributeType
{
    /**
     * Possible values of this enum
     */
    public const TEXT = 'TEXT';

    public const BOOLEAN = 'BOOLEAN';

    public const INTEGER = 'INTEGER';

    public const FLOAT = 'FLOAT';

    public const DATE = 'DATE';

    public const OBJECT = 'OBJECT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TEXT,
            self::BOOLEAN,
            self::INTEGER,
            self::FLOAT,
            self::DATE,
            self::OBJECT
        ];
    }
}


